### ISSUE TITLE
[Question] Twitter

### ISSUE THREAD

**Issue by Motzumoto** [abghorba/Robinhood-Trading-Bot#5]
because elon musk runs twitter, the twitter api is now behind a very massive paywall. Now my question is, do we need to provide twitter api keys? Is it at all necessary?

**Comment by abghorba** [comment]
Hi @Motzumoto,

Thanks for opening the issue and checking out this repository. I've updated the README to show that supplying Twitter API keys is optional. It's only necessary to provide these keys if you want to use the Twitter Sentiment bot.
